@ECHO OFF
ECHO.
ECHO CLOSE GOOGLE DRIVE
TASKKILL /F /IM googledrivesync.exe
ECHO.

ECHO CLOSE ONE DRIVE
TASKKILL /F /IM OneDrive.exe
ECHO.

ECHO CLOSE AMAZON DRIVE
TASKKILL /F /IM AmazonDrive.exe
ECHO.

ECHO CLOSE DROPBOX
TASKKILL /F /IM Dropbox.exe
ECHO.

ECHO CLOSE BACKBLAZE
TASKKILL /F /IM bzbui.exe
ECHO.

ECHO CLOSE CHROME
TASKKILL /F /IM chrome.exe
ECHO.

ECHO CLOSE GOOGLE UPDATE
TASKKILL /F /IM "GoogleUpdate.exe"
ECHO.

ECHO CLOSE INTERNET EXPORER
TASKKILL /F /IM iexplore.exe
ECHO.

ECHO CLOSE CREATIVE CLOUD
TASKKILL /F /IM "Creative Cloud.exe"
ECHO.

ECHO CLOSE ADOBE UPDATE SERVICE
TASKKILL /F /IM "AdobeUpdateService.exe"
ECHO.

ECHO DONE

PAUSE